<?php

namespace NativeRent\Common\Integration\API\Payloads;

final class AuthPayload {
	/**
	 * Partner domain.
	 *
	 * @var string
	 */
	private $domain;

	/**
	 * Partner login.
	 *
	 * @var string
	 */
	private $login;

	/**
	 * Partner password.
	 *
	 * @var string
	 */
	private $password;

	/**
	 * Secret key generated by plugin.
	 *
	 * @var string
	 */
	private $secretKey;

	/**
	 * @param  string $domain
	 * @param  string $login
	 * @param  string $password
	 * @param  string $secretKey
	 */
	public function __construct(
		$domain,
		$login,
		#[\SensitiveParameter]
		$password,
		#[\SensitiveParameter]
		$secretKey
	) {
		$this->domain = $domain;
		$this->login = $login;
		$this->password = $password;
		$this->secretKey = $secretKey;
	}

	/**
	 * @return string
	 */
	public function getDomain() {
		return $this->domain;
	}

	/**
	 * @return string
	 */
	public function getLogin() {
		return $this->login;
	}

	/**
	 * @return string
	 */
	public function getPassword() {
		return $this->password;
	}

	/**
	 * @return string
	 */
	public function getSecretKey() {
		return $this->secretKey;
	}
}
